services:
  mysql:
    image: mysql:8
    container_name: innovatech-examen-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - academia-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  backend-despachos:
    build: ./backend/back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    image: innovatech-back-despachos:1.0
    container_name: innovatech-examen-back-despachos
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - academia-net
    restart: unless-stopped

  backend-ventas:
    build: ./backend/back-Ventas_SpringBoot/Springboot-API-REST
    image: innovatech-back-ventas:1.0
    container_name: innovatech-examen-back-ventas
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - academia-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/front_despacho
    image: innovatech-frontend:1.0
    container_name: innovatech-examen-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-despachos
      - backend-ventas
    networks:
      - academia-net
    restart: unless-stopped

volumes:
  mysql_data:
    name: innovatech_examen_mysql_data

networks:
  academia-net:
    driver: bridge